name: Publish "More Than Code"

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Calibre
      run: sudo apt update && sudo apt install calibre

    - name: Publish ePub
      run: make book

    - name: Publish Mobi
      run: make mobi

    - name: Publish PDF
      run: make pdf

