name: Publish "More Than Code"

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Calibre and Pandoc
      run: sudo apt update && sudo apt install calibre pandoc

    - name: Publish ePub
      run: make book

    - name: Publish Mobi
      run: make mobi

    - name: Publish PDF
      run: make pdf

    - name: Commit new editions
      run: |
        GIT_STATUS=$(git status --porcelain)
        echo $GIT_STATUS
        git add ebook/
        if [ "$GIT_STATUS" != "" ]; then git commit -m "Published new editions"; fi
        if [ "$GIT_STATUS" != "" ]; then git push; fi
